// Generated by CoffeeScript 2.0.3
(function() {
  var Circle;

  Circle = class Circle extends Element {
    constructor(snap1, x1, y1, r1, id1, color1, obj1) {
      super(snap, x, y, r, id, color, obj);
      this.snap = snap1;
      this.x = x1;
      this.y = y1;
      this.r = r1;
      this.id = id1;
      this.color = color1;
      this.obj = obj1;
    }

    render() {
      return this.obj = this.snap.circle(this.x, this.y, this.r).attr({
        id: this.id,
        fill: this.color
      });
    }

  };

}).call(this);
