// Generated by CoffeeScript 2.0.3
(function() {
  var Element;

  Element = class Element {
    constructor() {}

    move(dx, dy) {
      return this.obj.attr({
        cx: +dx,
        cy: +dy
      });
    }

    start() {}

    stop() {
      var x, y;
      x = this.obj.attr("cx");
      y = this.obj.attr("cy");
      return this.obj.attr({
        cx: +x,
        cy: +y
      });
    }

    drag() {
      return this.obj.drag();
    }

    changeColor(color) {
      return this.obj.attr({
        fill: color
      });
    }

    showColorMenu() {}

  };

}).call(this);
