// Generated by CoffeeScript 2.0.3
(function() {
  $(function() {
    var hole, paper, r, x, y;
    paper = Snap(1000, 2000);
    x = 100; //or last saved state (how to)
    y = 100;
    r = 100;
    hole = new Circle(paper, x, y, r, 0, "#fc0");
    hole.render();
    hole.drag();
    return hole.obj.dblclick(function() {
      return hole.changeColor("red");
    });
  });

}).call(this);
