// Generated by CoffeeScript 2.0.3
(function() {
  var BJT, Boost, Buck, Capacitor, Comparator, Component, Current, Diode, InAmp, Inductor, JFET, MOSFET, OpAmp, Resistor, Transformer, Voltage;

  Component = class Component {
    constructor() {}

    get() {}

    render() {}

  };

  Resistor = class Resistor extends Component {
    constructor() {}

  };

  Capacitor = class Capacitor extends Component {
    constructor() {}

  };

  Inductor = class Inductor extends Component {
    constructor() {}

  };

  Voltage = class Voltage extends Component {
    constructor() {}

  };

  Current = class Current extends Component {
    constructor() {}

  };

  Diode = class Diode extends Component {
    constructor() {}

  };

  OpAmp = class OpAmp extends Component {
    constructor() {}

  };

  Comparator = class Comparator extends Component {
    constructor() {}

  };

  InAmp = class InAmp extends Component {
    constructor() {}

  };

  BJT = class BJT extends Component {
    constructor() {}

  };

  MOSFET = class MOSFET extends Component {
    constructor() {}

  };

  JFET = class JFET extends Component {
    constructor() {}

  };

  Transformer = class Transformer extends Component {
    constructor() {}

  };

  Buck = class Buck extends Component {
    constructor() {}

  };

  Boost = class Boost extends Component {
    constructor() {}

  };

}).call(this);
