// Generated by CoffeeScript 2.0.3
(function() {
  var Hole;

  Hole = class Hole {
    constructor(x, y, r) {
      this.x = x;
      this.y = y;
      this.r = r;
    }

    render(snap, id) {
      return snap.circle(this.x, this.y, this.r).attr({
        id: id
      });
    }

  };

}).call(this);
