// Generated by CoffeeScript 1.12.5
(function() {
  var Hole;

  Hole = (function() {
    function Hole() {}

    Hole.prototype.render = function(snap, x, y, r, tag) {
      var hole;
      return hole = snap.circle(x, y, r).attr({
        id: tag
      });
    };

    return Hole;

  })();

}).call(this);
