// Generated by CoffeeScript 2.0.3
(function() {
  var Breadboard;

  Breadboard = class Breadboard {
    constructor(num_ends, num_mids, num_rows, num_columns) {
      this.num_ends = num_ends;
      this.num_mids = num_mids;
      this.num_rows = num_rows;
      this.num_columns = num_columns;
    }

    render() {}

  };

}).call(this);
