// Generated by CoffeeScript 2.0.3
(function() {
  $(function() {
    var paper;
    return paper = Snap(1000, 2000);
  });

  //EXAMPLE OF SELECTING BITCH ASS HOE COMPONENTS
// var textElems = s.selectAll('.text'),
//         amount = 20/textElems.length;

// // Loops through each element
// for (var i = 1; i < textElems.length; i++) {

//     // Initiates the animation to translate to the correct position
//     textElems[i].animate({
//         'transform': 't' + (amount * i) + ',-' + (amount * i)
//     }, 200, mina.easeinout);
// };

}).call(this);
